language: node_js
node_js:
    - 'lts/*'

cache:
    directories:
        - node_modules

install:
    - npm install
    - npm install codecov -g

script:
    - npm run validate

after_success:
    - codecov

branches:
    only:
        - master
